--- # My First YAML Playbook
- hosts: demo
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
   - name: Install HTTPD server on centos 7
     action: yum name=httpd state=installed
