--- # Tag functionality playbook
- hosts: demo
  user: ansible
  sudo: yes
  connection: ssh
  tasks:
    - name: first name
      raw: echo "ADAM " > /tmp/LOG
      tags:
       - firstname
    - name: second name
      raw: echo "M " > /tmp/LOG
      tags:
        - secondname

