- name: Install Apache on centos
  yum: pkg='{{ redhat_apache}}' state=latest
  when: ansible_os_family == "RedHat"
  notify: Restart Apache
- name: Install Apache on ubuntu
  apt: pkg=apache2 state=latest
  when: ansible_os_family == "Debian"
